// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "xxxxxxxxxxxxxxxxxxxxxxxxxx";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMoistureLowChange();
void onPlantSelectChange();
void onPumpRuntimeChange();
void onPumpOnChange();

String status;
int moisture0;
int moisture1;
int moisture2;
int moisture3;
int moisture4;
int moisture_low;
int plant_select;
int pump_runtime;
bool pump_on;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture_low, READWRITE, ON_CHANGE, onMoistureLowChange);
  ArduinoCloud.addProperty(plant_select, READWRITE, ON_CHANGE, onPlantSelectChange);
  ArduinoCloud.addProperty(pump_runtime, READWRITE, ON_CHANGE, onPumpRuntimeChange);
  ArduinoCloud.addProperty(pump_on, READWRITE, 1 * SECONDS, onPumpOnChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
